AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for TextTunesLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  RecommendationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        Recommend:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recommend
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./recommendation
      DockerTag: python3.10-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RecommendationFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for RecommendationFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recommend/"
  RecommendationFunction:
    Description: "RecommendationFunction Lambda Function ARN"
    Value: !GetAtt RecommendationFunction.Arn
  RecommendationFunctionRole:
    Description: "Implicit IAM Role created for Recommendation function"
    Value: !GetAtt RecommendationFunctionRole.Arn
