name: Train ML model
on:
  push: 
    paths:
    - "'Recommendation Algo'\notebook.ipynb"
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Install Dependencies
        run: |
          pip install -r 'Recommendation Algo'/requirements.txt
      - name: Convert Notebook to python file
        run: |
          jupyter nbconvert --to script 'Recommendation Algo'/notebook.ipynb
      - name: Train Model
        run: |
          python 'Recommendation Algo'/notebook.py
          ls 'Recommendation Algo'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
