name: Train ML model

on:
  push: 
    paths:
      - 'Recommendation Algo/notebook.ipynb'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install -r 'Recommendation Algo/TextTunesLambda/recommendation/requirements.txt'
          python -m pip install jupyter nbconvert nbformat
          pip install kaggle
      - name: Download Kaggle dataset
        run: |
          sudo mkdir -p /kaggle/input/spotify-million-song-dataset
          sudo mkdir -p /kaggle/input/spotify-12m-songs
          sudo kaggle datasets download -p /kaggle/input/spotify-million-song-dataset --unzip notshrirang/spotify-million-song-dataset 
          sudo kaggle datasets download -p /kaggle/input/spotify-12m-songs --unzip rodolfofigueroa/spotify-12m-songs
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download Kaggle datasets."
            exit 1
          fi
        env:
          KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
          KAGGLE_KEY: ${{ secrets.KaggleKey }}
      - name: Convert Notebook to python file
        run: |
          jupyter nbconvert --to script 'Recommendation Algo/notebook.ipynb'
      - name: Train Model
        run: |
          python 'Recommendation Algo/notebook.py'
          ls 'Recommendation Algo'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
