name: Train ML model

on:
  push: 
    paths:
      - 'Recommendation Algo/notebook.ipynb'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install -r 'Recommendation Algo/TextTunesLambda/recommendation/requirements.txt'
      - name: Convert Notebook to python file
        run: |
          jupyter nbconvert --to script 'Recommendation Algo/notebook.ipynb'
      - name: Train Model
        run: |
          python 'Recommendation Algo/notebook.py'
          ls 'Recommendation Algo'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
